config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts, only: %i[index show]
  namespace :admin do
    root 'dashboard#index'
    get '/dashboard', to: 'dashboard#index'
    get '/sign_in', to: 'sessions#new'
    delete '/sign_out', to: 'sessions#destroy'
    resources :posts
    resources :registrations, only: %i[new create]
    resources :sessions, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_ancestry
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user

  acts_as_taggable

  validates :title, presence: true
  validates :content, presence: true

  paginates_per 20

  scope :index_all, -> {
    select(:id, :title, :updated_at, :user_id, :category_id)
      .order(updated_at: :desc)
      .includes(:user, :category)
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :nullify
  acts_as_authentic
  enum role: { normal: 0, admin: 1 }
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  secure Rails.env.production?
  httponly true
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout 'admin/layouts/application'
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    require_login
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_post, only: %i[index new create]
  after_action :verify_authorized

  def index
    @posts = Post.index_all.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to([:admin, @post], success: '作成完了')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to([:admin, @post], success: '更新完了')
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_path, success: '削除完了'
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :tag_list)
  end

  def authorize_post
    authorize Post
  end
end

app/controllers/admin/registrations_controller.rb
class Admin::RegistrationsController < Admin::ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to admin_root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  include Pundit
  before_action :set_view_path
  protect_from_forgery with: :exception

  helper_method :current_user_session, :current_user

  private

  def set_view_path
    path = request.smart_phone? ? 'mobile' : 'pc'
    prepend_view_path(Rails.root + 'app/views' + path)
  end

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session &. user
  end

  def require_login
    return redirect_to admin_sign_in_path unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show]

  def index
    @posts = Post.page(params[:page])
  end

  def show
  end

  private

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password)
  end
end

app/helpers/amp_helper.rb
module AmpHelper
  def amp_css
    controller = params[:controller]
    return Rails.application.assets["mobile/#{controller}"].to_s.html_safe if Rails.env.development?
    File.read "#{Rails.root}/public#{stylesheet_path("mobile/#{controller}", host: nil)}"
  end

  def render_css(path)
    raw Sass::Engine.for_file("#{Rails.root}/app/assets/stylesheets/#{path}", load_paths: ["#{Rails.root}/app/assets/stylesheets"], style: :compressed).to_css
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: Settings.site.name,
      reverse: true, # タイトルタグ内の表記順をページタイトル|サイトタイトルの順にする
      title: Settings.site.page_title,
      description: Settings.site.page_description,
      og: default_og
    }
  end

  def format_date_by_dot(date)
    date.strftime('%Y.%m.%d')
  end

  def format_date_by_slash(date)
    date.strftime('%Y/%m/%d')
  end

  private

  def default_og
    {
      title: :title,
      type: Settings.site.og.type,
      url: request.original_url,
      image: image_url(Settings.site.og.image_path),
      site_name: Settings.site.name,
      description: :description,
      locale: 'ja_JP'
    }
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def amp_url(url)
    amp_uri = URI.parse(url)
    amp_uri.path = "#{amp_uri.path}.amp" unless amp_uri.path.end_with?('amp')
    amp_uri.query = h(amp_uri.query) if amp_uri.query.present?
    amp_uri
  end

  def canonical_url(url)
    canonical_uri = URI.parse(url)
    canonical_uri.path = canonical_uri.path.sub(/\.amp$/, '') if canonical_uri.path.end_with?('amp')
    canonical_uri.query = h(canonical_uri.query) if canonical_uri.query.present?
    canonical_uri
  end
end

app/views/admin/dashboard/index.html.slim
.container
  .row
    = render 'admin/shared/sidebar'
    main.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
      h1.page-header Dashboard

app/views/admin/layouts/_header.html.slim
header
  nav.navbar.navbar-inverse.navbar-fixed-top
    .navbar-header
      = link_to "Admin", admin_root_path, class: "navbar-brand"

app/views/admin/layouts/_meta_tags.html.slim
meta charset='UTF-8'
meta name="viewport" content="width=device-width, initial-scale=1"

= display_meta_tags(default_meta_tags)
= csrf_meta_tags

app/views/admin/layouts/application.html.slim
doctype html
html lang="ja"
  head
    = render 'admin/layouts/meta_tags'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  body
    = render 'admin/layouts/header'
    = yield

app/views/admin/posts/_form.html.slim
= form_with(model: [:admin, post], local: true) do |f|
  - if post.errors.any?
    - post.errors.full_messages.each do |message|
      li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label :content
    = f.text_area :content, class: "form-control", rows: "30"

  .form-group
    = f.label :category
    = f.text_field :category_id, class: "form-control"

  .form-group
    = f.label :tag_list
    = text_field_tag 'post[tag_list]', post.tag_list.join(","), class: "form-control"

  = f.submit class: "btn btn-default"

app/views/admin/posts/edit.html.slim
.container
  .row
    = render 'form', post: @post

    = link_to "一覧", admin_posts_path
    = link_to "詳細", [:admin, @post]

app/views/admin/posts/index.html.slim
.container-fluid
  .row
    = render 'admin/shared/sidebar'

    main.col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
      = render 'admin/shared/flash'
      h1.page-header 投稿
      = button_to "新規作成", new_admin_post_path, class: "btn btn-default", method: :get
      div.table-responsive
        table.table.table-striped
          thead
            tr
              th.col-sm-6.col-md-6 タイトル
              th.col-sm-1.col-md-1 作成者
              th.col-sm-1.col-md-1 カテゴリ
              th.col-sm-1.col-md-1 更新時間

          tbody
            - @posts.each do |post|
                tr
                  td = link_to post.title, admin_post_path(post.id)
                  td = post.user.email
                  td = post.category.name
                  td = format_date_by_slash(post.updated_at)

      = paginate(@posts)

app/views/admin/posts/new.html.slim
.container
  .row
    = render 'form', post: @post

    = link_to "一覧", admin_posts_path

app/views/admin/posts/show.html.slim
.container
  .row
    = render 'admin/shared/flash'

    p = @post.title

    p = @post.content.html_safe

    p = @post.category.name

    p
      - @post.tag_list.each do |tag|
        = tag

    p = format_date_by_dot(@post.updated_at)

    = link_to "一覧", admin_posts_path
    = link_to "編集", edit_admin_post_path(@post)
    = button_to "削除", admin_post_path(@post), method: :delete, class: "btn btn-danger"

app/views/admin/shared/_flash.html.slim
- flash.each do |name, msg|
  = content_tag :div, class: "alert bg-#{name}"
    = msg
    button.close data-dismiss="alert"
      span aria-hidden="true" &times;

app/views/admin/shared/_sidebar.html.slim
nav.col-sm-3.col-md-2.sidebar
  = button_to 'Sign Out', admin_sign_out_path, method: :delete, class: 'btn btn-default'
  ul.nav.nav-sidebar
    li
      = link_to "投稿", admin_posts_path
    li class="nav-item"
      a href="#" 画像

app/views/mobile/layouts/_header.html.slim
header.ampstart-headerbar.fixed.flex.justify-start.items-center.top-0.left-0.right-0.pl2.pr4
  =amp_image_tag("logo.png", width: "100", height: "61.3", layout: "fixed", alt: "The Blog", class: "my0 mx-auto")

app/views/mobile/layouts/_meta_tags.html.slim
meta charset='UTF-8'
meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1"
link rel='canonical' href = canonical_url(request.url).to_s.html_safe
style[amp-boilerplate]
      | body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}
noscript
  style[amp-boilerplate]
    | body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}
script[custom-element="amp-carousel" src="https://cdn.ampproject.org/v0/amp-carousel-0.1.js" async=""]
script[custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js" async=""]
script[custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js" async=""]
script[custom-element="amp-form" src="https://cdn.ampproject.org/v0/amp-form-0.1.js" async=""]
script[custom-element="amp-instagram" src="https://cdn.ampproject.org/v0/amp-instagram-0.1.js" async=""]
style[amp-custom]
  = render_css('mobile/normalize.scss')
  = amp_css
script[async src="https://cdn.ampproject.org/v0.js"]

app/views/mobile/layouts/application.html.slim
doctype html
html amp="" lang="ja"
  head
    = render 'layouts/meta_tags'
  body
    = render 'layouts/header'
    = yield

app/views/mobile/posts/index.html.slim
main
  h2.mb1.px3
    | Mobile

  - @posts.each do |post|
    p.mb4.px3
      | タイトル：
      = link_to post.title, post
    p.mb4.px3
      | 更新日時：
      = format_date_by_slash(post.updated_at)

  = paginate(@posts)

app/views/mobile/posts/show.html.slim
section
  =amp_image_tag("sample.jpg", width: "1600", height: "1066", layout: "responsive", alt: "Smaple", class: "mb3")

p = format_date_by_dot(@post.updated_at)
h2.mb4 = @post.title
p.mb4 = @post.content.html_safe

= link_to :index, posts_path

app/views/pc/layouts/_meta_tags.html.slim
meta charset='UTF-8'
link rel="amphtml" href = amp_url(request.url).to_s.html_safe
= display_meta_tags(default_meta_tags)

app/views/pc/layouts/_rails_default.html.slim
= csrf_meta_tags
= stylesheet_link_tag 'pc/application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'pc/application', 'data-turbolinks-track': 'reload'

app/views/pc/layouts/application.html.slim
doctype html
html
  head
    = render 'layouts/meta_tags'
    = render 'layouts/rails_default'
  body
    = yield

app/views/pc/posts/_form.html.slim
= form_with(model: post, local: true) do |f|
  - if post.errors.any?
    - post.errors.full_messages.each do |message|
      li = message

  = f.label :title
  = f.text_field :title
  = f.label :content
  = f.text_area :content
  = f.label :category_id
  = f.text_field :category_id
  = f.label :tag_list
  = text_field_tag 'post[tag_list]', post.tag_list.join(",")

  = f.submit

app/views/pc/posts/index.html.slim
= render 'shared/flash'

h1
  | PC
- @posts.each do |post|
  p
    | タイトル：
    = link_to post.title, post
  p
    | 更新日時：
    = format_date_by_slash(post.updated_at)

= paginate(@posts)

- if policy(@posts).new?
  = link_to :new, new_post_path

app/views/pc/posts/show.html.slim
p
  | タイトル：
  = @post.title

p
  | 内容：
  = @post.content.html_safe

p
  | カテゴリ：
  = @post.category.name

p
  | タグ：
  - @post.tag_list.each do |tag|
    = tag

p
  | 更新日時：
  = format_date_by_dot(@post.updated_at)

= link_to :index, posts_path